### PR TITLE
feat: Bootstrap Operate-first

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/community/issues/36

/hold

requires `labels.yaml` to be imported. 

Depends on: https://github.com/thoth-station/thoth-application/pull/1611

### CODE REVIEW

**Comment by goern** [comment]
looks like you are in a flow... could you do that for thoth-station/core too? :)

Cc: @harshad16

**Comment by HumairAK** [comment]
> I see couple of mentions to the aicoe, (guessing this is a copy/paste), did you want to remove or keep those?

**Review by 4n4nd — COMMENTED** [review]
one small suggestion other than that lgtm

**Comment by tumido** [comment]
@HumairAK @4n4nd better now?

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Pull request merged**
