### PR TITLE
Update github-config.yaml

### PR DESCRIPTION
**Pull request by johwes**
Hi,

I work as a Solution Architect at Red Hat and I would like to join the Operate First community.

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve 

Welcome!

**Comment by HumairAK** [comment]
@harshad16 how do we fix the error here for peribolos do you know? 
```
error rendering spyglass page: error when resolving real path s3/thoth/prow-logs/pr-logs/pull/operate-first_common/71/peribolos/1497230661444964353: blob (key "prow-logs/pr-logs/pull/operate-first_common/71/peribolos/1497230661444964353.txt") (code=Unknown): InvalidAccessKeyId: The AWS access key Id you provided does not exist in our records.
	status code: 403, request id: l02rtoki-axhefw-o4m, host id: l02rtoki-axhefw-o4m
```

Is this related to the storage bucket change?

**Comment by harshad16** [comment]
@HumairAK yes it was due to storages
as we were using rick cluster storage temporarily, I have switched it back to Smaug.

seems like there some other peribolos issues going on

**Pull request merged**
