### PR TITLE
feat: Add community-handbook repo

### PR DESCRIPTION
**Pull request by tumido**
Resolves: https://github.com/operate-first/common/issues/6

please review and leave on hold for a coordinated merge, I want to create the repo from a template - which has to be done manually right now.
/hold

### CODE REVIEW

**Comment by tumido** [comment]
/override peribolos

seems like an upstream bug - dry run tries to create team and then list its members. Since the team is not actually created, it can't list the members and fails.

**Comment by tumido** [comment]
@goern any idea how the override command should work?
https://prow.operate-first.cloud/command-help

**Review by 4n4nd — COMMENTED** [review]
/lgtm

**Pull request merged**
