### PR TITLE
Format fixes and cruft cleanup

### PR DESCRIPTION
**Pull request by quaid**
This PR presumes the `labels.md` file isn't auto-generated. If it is, you can point me at the right place to make the formatting patch; the generation should pick up the recent changes in the `labels.yaml` file.

### CODE REVIEW

**Comment by goern** [comment]
uhh... complicated, as we need a Developer to generate the .md using some binary which is part of kubernetes/test-infra ... and as we need to commit the .md to the repo... it is most probably a human doing so.

```
$ pwd
/home/goern/Source/github.com/kubernetes/test-infra/label_sync
$ bazel run //label_sync -- --action docs \
   --config /home/goern/Work/thoth-station/core/community/labels.yaml \
   --docs-template /home/goern/Work/thoth-station/core/community/labels.md.tmpl \
   --docs-output /home/goern/Work/thoth-station/core/community/labels.md                                                            
```

@tumido do you think there is some resource to get this into a shell script and a `pre-build` tasks in the website publish pipeline?

**Comment by quaid** [comment]
>    --docs-template /home/goern/Work/thoth-station/core/community/labels.md.tmpl \

Ah, there's the template file, right in front of my nose!

I see where the missing linebreak is in there, I'll make a PR to fix that.

**Comment by tumido** [comment]
I'm commenting on the other PR, while a discussion is happening here. https://github.com/operate-first/common/pull/10#issuecomment-884853076

I think we can do something like that.. or at least include it into pre-commit or pre-submit tasks for now (to check there's no difference)

Let me file an issue for myself. #11

**Review by tumido — CHANGES_REQUESTED** [review]
stating the obvious: this file can't be edited manually

**Comment by tumido** [comment]
superseded by #10

**Pull request closed without merging**
