### PR TITLE
Procedure for adding a new service to a cluster

### PR DESCRIPTION
**Pull request by rynofinn**
If this is the wrong place for this documentation, I would appreciate pointers for where it might live more usefully.

### CODE REVIEW

**Comment by durandom** [comment]
/hold

@rynofinn I dont think this repo is the right place. Is `inception` a os-climate specific workload? If so I'd add this to the os-climate repo that contains inception specifics. Or, if there's only the deployment manifests in the `apps` repo, you can put it as a README into the `/apps/inception` folder

**Comment by rynofinn** [comment]
OK, that makes sense.  I'll close this pull request and put the document into the /apps/inception directory.

**Pull request closed without merging**
