### PR TITLE
Add myself @stefwalter as a member of Operate First

### PR DESCRIPTION
**Pull request by stefwalter**
This would allow me be assigned issues, create discussions,
and have CI run on my jobs. I'm working on the Open Source Services
aspect of Operate First.

As recommended by @[HumairAK](https://github.com/HumairAK)

https://github.com/operate-first/community/pull/154#issuecomment-1072489912

### CODE REVIEW

**Review by harshad16 — COMMENTED** [review]
/lgtm
:+1:

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
