### PR TITLE
Added schwesig to the members list

### PR DESCRIPTION
**Pull request by schwesig**
schwesig/tschwesi

### CODE REVIEW

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Review by tumido — APPROVED** [review]
/lgtm
/approve

**Review by tumido — CHANGES_REQUESTED** [review]
Actually, would you mind including the name in alphabetical order?

+ Rebase is needed

Additionally you can add yourself to the `contributors-core` team as well. :slightly_smiling_face:

**Pull request closed without merging**
