### PR TITLE
Adding my Github handle to the member list

### PR DESCRIPTION
**Pull request by PARTHSONI95**

### CODE REVIEW

**Comment by HumairAK** [comment]
Hey @PARTHSONI95 -- looks like this has failed the pre-commit, this is a CI Lint test that runs on every PR. You can also run this locally by following the instructions [here](https://github.com/operate-first/apps/blob/master/contributing.md#tests). To see the output of the test, you can click "details" in the failing test here: 

image

If you install pre-commit and run the command in the link above, it will auto correct the mistakes. In this case the error seems to stem from the "^M" carriage return character at the end of one of the entries you added (did you do this in windows? :) )

**Comment by PARTHSONI95** [comment]
Hello @HumairAK  - Oops, I will do the CI lint test locally. However, I used vim to edit it :D

**Review by HumairAK — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
