### PR TITLE
AI4CloudOps repo admin access

### PR DESCRIPTION
**Pull request by saadullah01**
I am a PhD student at BU working on AI4CloudOps project and I need admin access to contribute to this project.

### CODE REVIEW

**Comment by abyrne55** [comment]
/lgtm

@HumairAK Ack'd. @saadullah01 will be taking over the team lead position

**Comment by saadullah01** [comment]
@HumairAK can you please review this PR.

**Comment by HumairAK** [comment]
apologies this flew under my radar 
/retest

**Comment by HumairAK** [comment]
@saadullah01 can you also add yourself to the `members` list here: https://github.com/operate-first/common/blob/main/github-config.yaml#L18

**Comment by tumido** [comment]
Superseded by https://github.com/operate-first/common/pull/153

**Pull request closed without merging**
