### PR TITLE
Update github-config.yaml

### PR DESCRIPTION
**Pull request by jacobarcarola**
Added Jacob Cole (jacobarcarola) to github-config.yaml member list

### CODE REVIEW

**Review by schwesig — COMMENTED** [review]
/lgtm

**Comment by tumido** [comment]
/override community-management/prow/peribolos

Failure unrelated, fix is on the way in a sec. :slightly_smiling_face:

**Comment by tumido** [comment]
CI failure should be resolved by https://github.com/operate-first/common/pull/123

**Pull request merged**
